name: Run Jest on Push

on:
  push:
    branches-ignore: [none]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint

    - name: Run Jest
      run: npm run test